name: hello custom action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Get details
      id: details
      uses: raunakgurud09/action-hello@v3
      with:
        name: "john doe"
        topic: "run from hello yml"
        secret: ${{secrets.SECRET}}
    - name: Get get output
      run: echo "The time was ${{steps.details.output.time}} message ${{steps.details.output.message}}"