name: hello custom action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Get details
      uses: raunakgurud09/action-hello@v2
      with:
        name: "john doe"
        topic: "run from hello yml"
        secret: ${{secrets.SECRET}}
    - name: Get get output
      run: echo "the time was ${{steps.hello.output.time}} message ${{steps.hello.output.message}}"