name: hello custom action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Get details
      uses: raunakgurud09/action-hello@v1
        with:
          name: "john doe"
          topic: "run from hello yml"
          secret: ${{secrets.SECRET}}
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'